generating code coverage report
Change-Id: Iecb9dadbaaaf480e6ca2e29e4f02006921855092

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -3,8 +3,7 @@
     builders:
       - shell: "/usr/local/jenkins/slave_scripts/gerrit-git-prep.sh https://review.openswitch.net git://git.openswitch.net"
 
-- builder:
-    name: branch-git-prep
+- builder:    name: branch-git-prep
     builders:
       - shell: |
           #!/bin/bash
@@ -431,6 +430,33 @@
            sudo chown jenkins.jenkins build/test/legacy/test-results.xml
 
 - builder:
+    name: generate-code-coverage
+    builders:
+      - shell: |
+           #!/bin/bash -x
+           set +x
+           git clone -b $OPS_BUILD_BRANCH https://git.openswitch.net/openswitch/ops-build .
+           # Setup the shared state local cache
+           export SSTATE_DIR=/mnt/jenkins/workspace/sstate-cache
+           mkdir -p /mnt/jenkins/workspace/sstate-cache
+           # Check if we need to configure
+           if [ ! -f .platform ] ; then
+             make configure genericx86-64
+           fi
+
+           set -e
+           # clean up .xml
+           rm -rf build/*-test-results.xml
+           # Prepare the test environment
+           touch .devenv
+           make testenv_init
+           make {module}-generate_coverage_report
+           # Cleanup
+           test -e .sandbox_uuid && make devenv_ct_clean
+           /usr/local/jenkins/slave_scripts/docker_clean_instances_and_image.sh $TOPOLOGY_TEST_IMAGE
+           sudo chown jenkins.jenkins build/test/legacy/test-results.xml
+
+- builder:
     name: fttest-for-image
     builders:
       - shell: |
@@ -589,6 +615,30 @@
            else
              echo "Skipping tests because it is not a genericx86-64 platform"
            fi
+
+- builder:
+    name: code-coverage-test
+    builders:
+      - shell: |
+	   #!/bin/bash -x
+           set -e
+           if git ls-remote https://git.openswitch.net/openswitch/ops | grep -swq "$ZUUL_BRANCH" ; then
+             OPS_BRANCH=$ZUUL_BRANCH
+           else
+             OPS_BRANCH=master
+           fi
+           rm -rf build/test/*/test-results.xml
+           cd src/{module}
+           cat extension.txt
+           if [ {platform} == "genericx86-64" ]
+           then
+             cd $WORKSPACE
+             touch .devenv
+             make {module}-clean
+             touch build/devenv-coverage-enabled
+             make testenv_init
+	     make {module}-generate_coverage_report
+
 
 - builder:
     name: module-test
