Adding   new checks for on demand CIT
Change-Id: Ia9665ea01da10799ef735e95ede18cf660713d08

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -286,8 +286,12 @@
            set +x
            # Identify the branch to use for the build system
            if git ls-remote https://git.openswitch.net/openswitch/ops-build | grep -swq "$Feature_BranchName" ; then
+              echo "Checking if $Feature_BranchName exists in ops-build repository"
               OPS_BUILD_BRANCH=$Feature_BranchName
            else
+              echo "****************************************************************************************"
+              echo "WARNING: cannot find $Feature_BranchName in ops-build, so using master branch instead"
+              echo "****************************************************************************************"
               OPS_BUILD_BRANCH=master
            fi
            echo "===================  Building ops-build on $OPS_BUILD_BRANCH =================== "
@@ -305,13 +309,23 @@
            rm -rf src/*
            for i in $Repositories_List
             do
-                if git ls-remote https://git.openswitch.net/openswitch/ops-build | grep -swq "$Feature_BranchName" ; then
+                if git ls-remote https://git.openswitch.net/openswitch/$i | grep -swq "$Feature_BranchName" ; then
+                    echo "Checking if $Feature_BranchName exists in ops-build repository"
                     OPS_BUILD_BRANCH=$Feature_BranchName
                 else
-                    OPS_BUILD_BRANCH=master
+                    echo "****************************************************************************************"
+                    echo "WARNING: cannot find $Feature_BranchName in ops-build, so aborting the build. "
+                    echo "Please provide a Feature Branch name and try again. Please make sure the Feature Branch exists on all of the Repositories you are giving"
+                    echo "****************************************************************************************"
+                    exit 1
                 fi
-           git clone -b $OPS_BUILD_BRANCH http://git.openswitch.net/openswitch/$i src/$i > /dev/null 2>&1
+           if [ $? -eq 0 ] ; then
+              git clone -b $OPS_BUILD_BRANCH http://git.openswitch.net/openswitch/$i src/$i > /dev/null 2>&1
+           else
+              exit 1
+           fi
            done
+           if [ $? -eq 0 ] ; then
            set -e
            # clean up .xml
            rm -rf build/*-test-results.xml
@@ -332,12 +346,23 @@
            Repositories_List=`echo $Repositories_List | sed -e 's#,# #'`
            for i in $Repositories_List
            do
-            echo "*************************************** Testing $i repo ***************************************"
-            make devenv_ct_test PY_TEST_ARGS="src/$i/tests --junit-xml=build/module-test-results.xml"  || (make devenv_ct_clean; docker rmi -f $VSI_IMAGE_NAME; exit 1)
+            if [ "$i" == "ops-build" ]; then
+            echo"No need to provide ops-build in List of repositories, skipping this step"
+            continue
+            else
+              if [ -d "$WORKSPACE/src/$i/tests" ]; then
+                 echo "*************************************** Testing $i repo ***************************************"
+                 make devenv_ct_test PY_TEST_ARGS="src/$i/tests --junit-xml=build/module-test-results.xml"  || (make devenv_ct_clean; docker rmi -f $VSI_IMAGE_NAME; exit 1)
+              else
+                 echo "Tests folder does not exist in $i repo, skip running tests"
+                 continue
+              fi
+            fi
            done
            test -e .sandbox_uuid && make devenv_ct_clean
            docker images | grep $VSI_IMAGE_NAME && docker rmi -f $VSI_IMAGE_NAME
            sudo chown jenkins.jenkins build/*-test-results.xml
+           fi
 
 - builder:
     name: fttest-for-image
