adding a new job to macros.yaml
this is an effort as part of the Commit reliability tests
to make sure we run a test case multiple times before it reaches
the gate job

Change-Id: I98b8233c92c94f8a4ed0f66cce054270883ce2ef
Signed-off-by: Akshar Ranka <akshar.ranka@hpe.com>

diff --git a/jenkins/jobs/macros.yaml b/jenkins/jobs/macros.yaml
--- a/jenkins/jobs/macros.yaml
+++ b/jenkins/jobs/macros.yaml
@@ -623,6 +623,82 @@
            fi
 
 - builder:
+    name: module-crt-cttest
+    builders:
+      - shell: |
+           #!/bin/bash -x
+           set +e
+           MOD_FRAMEWORK="^ops-tests/.*\.py$"
+           QUAGGA="^ops/tests/.*\.py$"
+           PATTERN="^tests/.*\.py$"
+           TEST_FAILURES=0
+           EXIT_FLAG=0
+
+           arr_files=($(git diff-tree --no-commit-id --name-only -r $ZUUL_COMMIT))
+
+           if git ls-remote https://git.openswitch.net/openswitch/ops | grep -swq "$ZUUL_BRANCH" ; then
+             OPS_BRANCH=$ZUUL_BRANCH
+           else
+             OPS_BRANCH=master
+           fi
+           rm -rf build/*-test-results.xml
+           cd src/{module}
+           cat extension.txt
+           if [ {platform} == "genericx86-64" ]
+           then
+             cd $WORKSPACE
+             rm -rf src/ops
+             echo "===================  Building Feature Tests from ops:$OPS_BUILD_BRANCH =================== "
+             git clone -b $OPS_BRANCH https://git.openswitch.net/openswitch/ops src/ops
+             make fs
+             make devenv_ct_init
+             y=`echo $JOB_NAME-$BUILD_NUMBER  | tr '[A-Z]' '[a-z]'`
+             export VSI_IMAGE_NAME=$y
+             echo $VSI_IMAGE_NAME > .image_name
+             make export_docker_image $VSI_IMAGE_NAME
+
+             for tst in "${arr_files[@]}"
+             do
+               echo $tst
+               TEST_FAILURES=0
+               if [[ $tst =~ $MOD_FRAMEWORK ]];
+               then
+                 continue
+               elif [[ $tst =~ $PATTERN ]] || [[ $tst =~ $QUAGGA ]];
+               then
+                 for run_count in {1..5}
+                 do
+                   make devenv_ct_test $WORKSPACE/src/{module}/$tst
+                   if [ $? != 0 ]
+                   then
+                     let TEST_FAILURES=$TEST_FAILURES+1
+                   fi
+                 done
+               fi
+               if [ $TEST_FAILURES != 0 ]
+               then
+                 EXIT_FLAG=1
+                 make devenv_ct_clean
+                 docker rmi -f $VSI_IMAGE_NAME
+                 make export_docker_image $VSI_IMAGE_NAME
+                 echo $tst
+                 echo " failure count: "
+                 echo $TEST_FAILURES
+               fi
+             done
+             if [$EXIT_FLAG != 1]
+             then
+               set -e
+               make devenv_ct_test PY_TEST_ARGS="src/{module}/tests --exitfirst --junit-xml=build/module-test-results.xml" || (make devenv_ct_clean; docker rmi -f $VSI_IMAGE_NAME; exit 1)
+               make devenv_ct_test PY_TEST_ARGS="src/ops/tests --exitfirst --junit-xml=build/feature-test-results.xml" || (make devenv_ct_clean; docker rmi -f $VSI_IMAGE_NAME; exit 1)
+             test -e .sandbox_uuid && make devenv_ct_clean
+             docker images | grep $VSI_IMAGE_NAME && docker rmi -f $VSI_IMAGE_NAME
+             sudo chown jenkins.jenkins build/*-test-results.xml
+           else
+             echo "Skipping cttest because it is not a genericx86-64 platform"
+           fi
+
+- builder:
     name: module-cttest-codecoverage
     builders:
       - shell: |
